# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: packages

r:
 - release
 - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - mkdir -p ~/.R
  - echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars

install:
  - R -e 'devtools::install_deps(dep = T, force_deps=TRUE)'
